name: Complete Check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Firefox
      uses: browser-actions/setup-firefox@v0.0.0
    - name: Install modules
      run: yarn
    - name: Run
      run: yarn pr
